### ISSUE TITLE
Automate the build and deploy workflow

### ISSUE THREAD

**Issue by shunta0213** [shunta0213/latex-docker#16]
Currently build & push workflow is dispatched by the tag push.

I want to run the build & push workflow dispatched by the commit push to the main branch.

```yaml
on:
  push:
    tags:
      - "v*"
```
